// functions/[[path]].ts
import { createPagesFunctionHandler } from "../tmp_modules/cloudflare-pages";

// @ts-ignore - Generated by `react-router build`
import * as build from "../build/server";

export const onRequest = createPagesFunctionHandler({ build });
